"""Generate docs/api.md from the python classes.

Run after changing the public API:

    python scripts/gen_api_docs.py
"""
import inspect
import pathlib
import sys

# runnable as `python scripts/gen_api_docs.py` from any directory
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from pylightcharts.history import InfiniteHistory
from pylightcharts import colors, indicators, overlay, shapes, themes
from pylightcharts.abstract import (
    AbstractChart, Area, Bar, Baseline, BridgeSeries, Candlestick, CustomSeries,
    GenericSeries, Histogram, Line, PriceLine, PriceScale, SeriesCommon,
)
from pylightcharts.headless import HeadlessChart
from pylightcharts.layout import Layout
from pylightcharts.table import Table
from pylightcharts.toolbox import ToolBox
from pylightcharts.topbar import TopBar
from pylightcharts.tooltips import Tooltip

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs' / 'api.md'

SECTIONS = [
    ('Chart', [AbstractChart, HeadlessChart]),
    ('Series', [SeriesCommon, Line, Histogram, CustomSeries, Area, Bar, Baseline]),
    ('Price scale and price lines', [PriceScale, PriceLine]),
    ('Widgets', [TopBar, Layout, ToolBox, Table, Tooltip, InfiniteHistory]),
    ('Indicator maths (`pylightcharts.indicators`)', None),
    ('Shape builders (`pylightcharts.shapes`)', None),
    ('Conditional colours (`pylightcharts.colors`)', None),
    ('Themes (`pylightcharts.themes`)', None),
    ('Two symbols (`pylightcharts.overlay`)', None),
]

def signature(func):
    try:
        return str(inspect.signature(func))
    except (TypeError, ValueError):
        return '(...)'


def describe(name, func):
    doc = inspect.getdoc(func) or ''
    summary = doc.split('\n\n')[0].replace('\n', ' ') if doc else ''
    return f'#### `{name}{signature(func)}`\n\n{summary}\n'


def class_section(cls):
    lines = [f'### `{cls.__name__}`', '']
    doc = inspect.getdoc(cls) or ''
    if doc:
        lines += [doc, '']
    seen = set()
    blocks = []
    for name, member in inspect.getmembers(cls, callable):
        if name.startswith('_') or name in seen:
            continue
        if not inspect.isfunction(member):
            continue
        seen.add(name)
        blocks.append(describe(name, member))
    lines += blocks
    return '\n'.join(lines)


def module_section(module):
    lines = []
    for name in getattr(module, '__all__', None) or dir(module):
        if name.startswith('_'):
            continue
        func = getattr(module, name, None)
        if not callable(func) or getattr(func, '__module__', '') != module.__name__:
            continue
        lines.append(describe(name, func))
    return '\n'.join(lines)


def main():
    parts = [
        '# API reference',
        '',
        'Generated by `scripts/gen_api_docs.py` — do not edit by hand.',
        '',
    ]
    for title, classes in SECTIONS:
        parts += [f'## {title}', '']
        if classes is None:
            module = next(m for m in (indicators, shapes, colors, themes, overlay)
                          if m.__name__.rsplit('.', 1)[-1] in title)
            parts.append(module_section(module))
        else:
            for cls in classes:
                parts.append(class_section(cls))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(parts), encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
